[phases.setup]
nixPkgs = ["nodejs-18_x", "npm"]

[phases.install]
cmds = ["cd server && npm ci"]

[phases.build]
cmds = ["cd server && npm run build --if-present"]

[start]
cmd = "cd server && npm start"

[variables]
NODE_ENV = "production"